### ISSUE TITLE
[FEATURE REQUEST] better location tracking

### ISSUE THREAD

**Issue by berthavekes2** [berthavekes2/home-assistant-config#4]
**Is your feature request related to a problem? Please describe.**
More accurate location tracking of persons

**Describe the solution you'd like**
Using input selects and more states

**Describe alternatives you've considered**
Increase consider_home time

**Additional context**

- [x] create input selects, with images

- [x] assign states

- [x] create automations for changing state

- [x] create automations for routines

- [x] vakantiemodes

**Comment by berthavekes2** [comment]
first setup done
